### ISSUE TITLE
Product Types Support

### ISSUE THREAD

**Issue by matthew-valenti** [hws47a/VF_EasyAjax#19]
This extension is brilliant!  Would love to see support for product types.

Layout xml containing product types are not processed i.e. <PRODUCT_TYPE_simple, <PRODUCT_TYPE_configurable, etc. in e.g. \app\design\frontend\rwd\default\layout\catalog.xml

Hack Fix:
Easy Ajax handles get added after the product type handles. So the update declared by the product type handles do not apply to the Easy Ajax handles. Extended the EasyAjax Response model and placed the handles before the type handles.

**Comment by hws47a** [comment]
Closing as Magento 1 is outdated and no features will be released.
